theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
title: '|) () |\/| | |\| | () |\|'
tagline: Insanely fast ECS for Java
description: Dominion is an Entity Component System library for Java
logo: dominion-logo-square.png
url: www.dominion.dev
