remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
title: '|) O M I N I O N'
tagline: An insanely fast ECS library for Java
description: An insanely fast ECS library for Java
logo: dominion-logo-square.png
url: www.dominion.dev
github:
  is_project_page: false
