remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
title: '|)()|\/|||\||()|\|'
tagline: Insanely fast ECS for Java
description: Dominion is an Entity Component System library for Java
logo: dominion-logo-square.png
url: www.dominion.dev
github:
  is_project_page: false
